import "server-only"

import { createClient } from "@/utils/supabase/server"

export type GeneratedArtifact = {
  contentType: string
  fileExtension: string
  buffer: Buffer
  fileName: string
}

// ----------------------------------------------------------------------------
// Pure TypeScript Standard PDF 1.4 Binary Generator
// ----------------------------------------------------------------------------
function escapePdfText(text: string): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/\(/g, "\\(")
    .replace(/\)/g, "\\)")
}

function toPdfSafeAscii(text: string): string {
  if (!text) return "-"
  return text
    .replace(/รายงานสรุปนักเรียน/g, "Student Summary Report")
    .replace(/รายงานกลุ่มเสี่ยง/g, "Risk and Early Warning Report")
    .replace(/รายงานการมาเรียน/g, "Attendance Summary Report")
    .replace(/รายงานผลการเรียน/g, "Academic Performance Report")
    .replace(/รายงาน/g, "Report")
    .replace(/ปกติ/g, "Normal")
    .replace(/ติดตาม/g, "Watch")
    .replace(/เสี่ยงสูง/g, "High-Risk")
    .replace(/ชาย/g, "Male")
    .replace(/หญิง/g, "Female")
    .replace(/มา/g, "Present")
    .replace(/ขาด/g, "Absent")
    .replace(/สาย/g, "Late")
    .replace(/ลา/g, "Leave")
    .replace(/ป่วย/g, "Sick")
    .replace(/ป\./g, "P.")
    .replace(/ม\./g, "M.")
    .replace(/[^\x20-\x7E]/g, "?")
}

export function buildStandardPdf(
  title: string,
  subtitle: string,
  schoolName: string,
  headers: string[],
  rows: string[][]
): Buffer {
  const safeTitle = toPdfSafeAscii(title)
  const safeSubtitle = toPdfSafeAscii(subtitle)
  const safeSchool = toPdfSafeAscii(schoolName)
  const safeHeaders = headers.map(toPdfSafeAscii)

  const contentStreamLines: string[] = []

  // Header
  contentStreamLines.push("BT")
  contentStreamLines.push("/F2 16 Tf")
  contentStreamLines.push("50 790 Td")
  contentStreamLines.push(`(${escapePdfText(safeTitle)}) Tj`)
  contentStreamLines.push("ET")

  contentStreamLines.push("BT")
  contentStreamLines.push("/F1 10 Tf")
  contentStreamLines.push("50 772 Td")
  contentStreamLines.push(`(School: ${escapePdfText(safeSchool)}  |  ${escapePdfText(safeSubtitle)}) Tj`)
  contentStreamLines.push("ET")

  // Header dividing line
  contentStreamLines.push("0.5 w")
  contentStreamLines.push("0.2 0.4 0.8 RG")
  contentStreamLines.push("50 760 m 545 760 l S")

  // Table coordinates
  let y = 740
  const colWidth = Math.floor(495 / Math.max(headers.length, 1))

  // Draw Table Header
  contentStreamLines.push("0.9 0.93 0.98 rg")
  contentStreamLines.push(`50 ${y - 4} 495 18 re f`)

  contentStreamLines.push("BT")
  contentStreamLines.push("/F2 9 Tf")
  contentStreamLines.push("0 0 0 rg")

  safeHeaders.forEach((h, i) => {
    const x = 54 + i * colWidth
    contentStreamLines.push(`1 0 0 1 ${x} ${y} Tm`)
    contentStreamLines.push(`(${escapePdfText(h.slice(0, 20))}) Tj`)
  })
  contentStreamLines.push("ET")

  // Header line
  contentStreamLines.push("0.5 w")
  contentStreamLines.push("0.7 0.7 0.7 RG")
  contentStreamLines.push(`50 ${y - 4} m 545 ${y - 4} l S`)

  y -= 18

  // Draw Table Rows
  const maxRows = Math.min(rows.length, 32)
  for (let r = 0; r < maxRows; r++) {
    const row = rows[r]
    const safeRow = row.map(toPdfSafeAscii)

    if (r % 2 === 1) {
      contentStreamLines.push("0.97 0.98 0.99 rg")
      contentStreamLines.push(`50 ${y - 3} 495 14 re f`)
    }

    contentStreamLines.push("BT")
    contentStreamLines.push("/F1 8.5 Tf")
    contentStreamLines.push("0.1 0.1 0.1 rg")

    safeRow.forEach((cell, i) => {
      const x = 54 + i * colWidth
      contentStreamLines.push(`1 0 0 1 ${x} ${y} Tm`)
      contentStreamLines.push(`(${escapePdfText(cell.slice(0, 22))}) Tj`)
    })
    contentStreamLines.push("ET")

    contentStreamLines.push("0.2 w")
    contentStreamLines.push("0.85 0.85 0.85 RG")
    contentStreamLines.push(`50 ${y - 3} m 545 ${y - 3} l S`)

    y -= 14
  }

  // Footer
  contentStreamLines.push("BT")
  contentStreamLines.push("/F1 8 Tf")
  contentStreamLines.push("0.5 0.5 0.5 rg")
  contentStreamLines.push(`50 40 Td`)
  contentStreamLines.push(`(Generated by SCIDAS  -  ${new Date().toISOString().slice(0, 10)}  -  Page 1 of 1) Tj`)
  contentStreamLines.push("ET")

  const streamContent = contentStreamLines.join("\n")
  const streamLength = Buffer.byteLength(streamContent, "utf8")

  const pdfBody = [
    "%PDF-1.4",
    "1 0 obj",
    "<< /Type /Catalog /Pages 2 0 R >>",
    "endobj",
    "2 0 obj",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "endobj",
    "3 0 obj",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595.28 841.89] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>",
    "endobj",
    "4 0 obj",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    "endobj",
    "5 0 obj",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
    "endobj",
    "6 0 obj",
    `<< /Length ${streamLength} >>`,
    "stream",
    streamContent,
    "endstream",
    "endobj",
  ]

  const offsets: number[] = []
  const fullText = pdfBody.join("\n") + "\n"

  const lines = fullText.split("\n")
  let currentOffset = 0
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]
    if (line.match(/^\d+ 0 obj$/)) {
      offsets.push(currentOffset)
    }
    currentOffset += Buffer.byteLength(line + "\n", "utf8")
  }

  const xref = [
    "xref",
    `0 ${offsets.length + 1}`,
    "0000000000 65535 f ",
    ...offsets.map((o) => `${String(o).padStart(10, "0")} 00000 n `),
    "trailer",
    `<< /Size ${offsets.length + 1} /Root 1 0 R >>`,
    "startxref",
    String(currentOffset),
    "%%EOF",
  ].join("\n")

  return Buffer.from(fullText + xref, "utf8")
}

// ----------------------------------------------------------------------------
// Pure TypeScript Standard CSV / Excel-Friendly Generator
// ----------------------------------------------------------------------------
export function buildCsvSpreadsheet(headers: string[], rows: string[][]): Buffer {
  const bom = "\uFEFF"
  const lines = [
    headers.map((h) => `"${h.replace(/"/g, '""')}"`).join(","),
    ...rows.map((r) => r.map((c) => `"${(c ?? "").replace(/"/g, '""')}"`).join(",")),
  ]
  return Buffer.from(bom + lines.join("\r\n"), "utf8")
}

// ----------------------------------------------------------------------------
// Report Data Fetchers & Master Generator
// ----------------------------------------------------------------------------
export async function generateReportArtifact(job: {
  id: string
  schoolId: string
  reportType: string
  title: string
  filters?: Record<string, unknown>
}): Promise<GeneratedArtifact> {
  const supabase = await createClient()

  // Load school info
  const { data: school } = await supabase
    .from("schools")
    .select("name, school_code")
    .eq("id", job.schoolId)
    .single()

  const schoolName = school?.name || "โรงเรียนขนาดเล็ก"

  let headers: string[] = []
  let rows: string[][] = []
  let subtitle = `วันที่สร้าง: ${new Date().toLocaleDateString("th-TH")}`

  switch (job.reportType) {
    case "student_summary": {
      headers = ["รหัสนักเรียน", "ชื่อ - นามสกุล", "ระดับชั้น/ห้อง", "สถานะความเสี่ยง", "สถิติมาเรียน", "เคสช่วยเหลือ"]
      const { data: students } = await supabase
        .from("v_student_worklist")
        .select("student_code, full_name, grade_level, classroom_name, risk_level, attendance_rate_30d, open_support_count")
        .eq("school_id", job.schoolId)
        .limit(200)

      if (students) {
        rows = students.map((s) => [
          s.student_code || "-",
          s.full_name || "-",
          s.classroom_name || s.grade_level || "-",
          s.risk_level === "high" ? "เสี่ยงสูง" : s.risk_level === "watch" ? "ติดตาม" : "ปกติ",
          s.attendance_rate_30d !== null ? `${s.attendance_rate_30d}%` : "-",
          s.open_support_count ? `${s.open_support_count} เคส` : "ปกติ",
        ])
      }
      subtitle += ` | นักเรียนทั้งหมด: ${rows.length} คน`
      break
    }

    case "risk_report":
    case "risk_assessment": {
      headers = ["รหัสนักเรียน", "ชื่อ - นามสกุล", "ห้องเรียน", "ระดับความเสี่ยง", "คะแนนความเสี่ยง", "จำนวนการแจ้งเตือน"]
      const { data: risks } = await supabase
        .from("v_student_worklist")
        .select("student_code, full_name, classroom_name, risk_level, risk_score, active_flag_count")
        .eq("school_id", job.schoolId)
        .in("risk_level", ["high", "watch"])
        .order("risk_score", { ascending: false })
        .limit(200)

      if (risks) {
        rows = risks.map((r) => [
          r.student_code || "-",
          r.full_name || "-",
          r.classroom_name || "-",
          r.risk_level === "high" ? "เสี่ยงสูง (High)" : "ต้องติดตาม (Watch)",
          r.risk_score ? String(r.risk_score) : "-",
          r.active_flag_count ? `${r.active_flag_count} รายการ` : "-",
        ])
      }
      subtitle += ` | พบนักเรียนกลุ่มเสี่ยง: ${rows.length} คน`
      break
    }

    case "attendance_report":
    case "attendance_summary": {
      headers = ["วันที่", "รหัสนักเรียน", "ชื่อ - นามสกุล", "ห้องเรียน", "สถานะการมาเรียน", "หมายเหตุ"]
      const { data: attendance } = await supabase
        .from("attendance_records")
        .select(`
          date, status, remark,
          students(student_code, first_name, last_name),
          classrooms(name)
        `)
        .eq("school_id", job.schoolId)
        .order("date", { ascending: false })
        .limit(200)

      if (attendance) {
        rows = attendance.map((a) => {
          const st = a.students as unknown as { student_code: string; first_name: string; last_name: string } | null
          const cl = a.classrooms as unknown as { name: string } | null
          const statusMap: Record<string, string> = {
            present: "มาเรียน",
            absent: "ขาดเรียน",
            late: "มาสาย",
            leave: "ลากิจ",
            sick: "ลาป่วย",
          }
          return [
            a.date || "-",
            st?.student_code || "-",
            `${st?.first_name || ""} ${st?.last_name || ""}`.trim() || "-",
            cl?.name || "-",
            statusMap[a.status] || a.status,
            a.remark || "-",
          ]
        })
      }
      subtitle += ` | รายการบันทึก: ${rows.length} รายการ`
      break
    }

    case "academic_report": {
      headers = ["รหัสนักเรียน", "ชื่อ - นามสกุล", "รายวิชา", "คะแนนเก็บ", "กลางภาค", "ปลายภาค", "รวม", "เกรด"]
      const { data: scores } = await supabase
        .from("academic_scores")
        .select(`
          classwork_score, midterm_score, final_score, total_score, grade,
          students(student_code, first_name, last_name),
          classroom_subjects(subjects(name, subject_code))
        `)
        .eq("school_id", job.schoolId)
        .order("created_at", { ascending: false })
        .limit(200)

      if (scores) {
        rows = scores.map((sc) => {
          const st = sc.students as unknown as { student_code: string; first_name: string; last_name: string } | null
          const cs = sc.classroom_subjects as unknown as { subjects: { name: string; subject_code: string } | null } | null
          return [
            st?.student_code || "-",
            `${st?.first_name || ""} ${st?.last_name || ""}`.trim() || "-",
            cs?.subjects?.name || "-",
            String(sc.classwork_score ?? "-"),
            String(sc.midterm_score ?? "-"),
            String(sc.final_score ?? "-"),
            String(sc.total_score ?? "-"),
            sc.grade || "-",
          ]
        })
      }
      subtitle += ` | ผลการเรียน: ${rows.length} รายการ`
      break
    }

    default: {
      headers = ["รหัสนักเรียน", "ชื่อ - นามสกุล", "ระดับชั้น", "สถานะ"]
      const { data: students } = await supabase
        .from("v_student_worklist")
        .select("student_code, full_name, classroom_name, risk_level")
        .eq("school_id", job.schoolId)
        .limit(100)

      if (students) {
        rows = students.map((s) => [
          s.student_code || "-",
          s.full_name || "-",
          s.classroom_name || "-",
          s.risk_level || "-",
        ])
      }
      break
    }
  }

  const pdfBuffer = buildStandardPdf(job.title, subtitle, schoolName, headers, rows)
  return {
    contentType: "application/pdf",
    fileExtension: "pdf",
    buffer: pdfBuffer,
    fileName: `${job.id}.pdf`,
  }
}
